server:
  port: 8001
  
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/tedu_store?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    
mybatis:
  config-location: classpath:mybatis/generatorConfig.xml
  mapper-locations: 
  - classpath:mybatis/mapper/*.xml
  

logging.level.cn.tedu.mapper: debug
#debug: true